exclude: .git
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-private-key
  - id: file-contents-sorter
    files: requirements.*\.in
  - id: mixed-line-ending
    args: [--fix, lf]
- repo: https://github.com/mrtazz/checkmake
  rev: 0.2.2
  hooks:
  - id: checkmake
#- repo: https://github.com/NixOS/nixfmt
#  rev: d0c0cda4fe6b7ae2b9aa37f3ee15e6412573eb01
#  hooks:
#  - id: nixfmt
